name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Get Flutter Dependencies
        run: flutter pub get

      - name: Update CocoaPods
        run: pod repo update
        working-directory: ios

      - name: Build iOS Release
        run: flutter build ios --release --no-codesign --split-debug-info=build/ios/debug-info --obfuscate --tree-shake-icons --icon-shaking

      - name: Create Payload Directory
        run: mkdir Payload
        working-directory: build/ios/iphoneos

      - name: Move App to Payload
        run: mv Runner.app Payload
        working-directory: build/ios/iphoneos

      - name: Create IPA
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload IPA to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"

      - name: Clean Up
        run: rm -rf build/ios/iphoneos/Payload
